services:
  db:
    image: postgres:15
    container_name: finance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_finance
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/alves/go/src/github.com/finance/db_data:/var/lib/postgresql/data
      - /c/Users/alves/go/src/github.com/finance/db/migration:/migration


