services:
  db:
    image: postgres:15
    container_name: finance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_finance
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data